# Reduce email spam
notifications:
  email: false

sudo: required

# Use clang++
env:
    - CXX="clang++"

# Handle submodules manually
git:
    submodules: false

# Replace SSH URLs with a public URL
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
compiler: clang
language: c

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
  - ctest -V

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libldns-dev
      - libuv1-dev
      - libjansson-dev
      - libmnl-dev
      - libsctp-dev 
